### ISSUE TITLE
Dinero materiales dohyo

### ISSUE THREAD

**Issue by Ruben-MR** [asrob-uc3m/ASROB-sumo#4]
Y con respecto a la otra issue y para que no se me olvide, hay que ver cómo repartir el gasto de los materiales del dohyo. No hay prisa, pero que tampoco se olvide...

**Comment by David-Estevez** [comment]
Gracias por poner la issue!! :clap: :clap:  Veamos...

Para empezar, comenta por aquí, para que quede constancia,  de qué materiales estamos hablando y cuánto te costaron.

Para la financiación se me ocurren dos formas:

* Opción 1: hacer bote entre todos los de RoboFactory / grupo de Sumo.
* Opción 2: si queda dinero en la hucha de ASROB, hacer una petición para que se financie desde ahí.

**Comment by Ruben-MR** [comment]
Pues en resumidas cuentas seria la madera, que fueron 18 euros en total, por ahora no se ha cogido nada mas. Lo unico que podria hacer falta seria el spray negro para pintarlo y cinta blanca para el borde, pero hasta el momento solo la madera.

**Comment by David-Estevez** [comment]
Bueno, para que esto avance, y @Ruben-MR pueda recuperar su dinero, he creado yo la votación en una issue de actas: https://github.com/asrob-uc3m/actas/issues/125

**Comment by Ruben-MR** [comment]
Asunto zanjado en su correspondiente issue de actas.
