### ISSUE TITLE
Revisión PCB sumo

### ISSUE THREAD

**Issue by Ruben-MR** [asrob-uc3m/ASROB-sumo#5]
Adjunto todos los archivos de kicad necesarios para la PCB del sumo para el visto bueno antes de su encargo.

[Sumobot.zip](https://github.com/asrob-uc3m/ASROB-sumo/files/1912191/Sumobot.zip)

**Comment by Ruben-MR** [comment]
Ya de paso si es posible echar un vistazo a la parte de la estructura para imprimir, está en el repo, en la branch correspondiente, pero lo subo aquí también.

[FreeCAD.zip](https://github.com/asrob-uc3m/ASROB-sumo/files/1912195/FreeCAD.zip)

**Comment by David-Estevez** [comment]
Sube los archivos al repositorio en lugar de la issue porfa, así tenemos un historial de las versiones de la placa. 

Me pongo a revisarlo en cuanto pueda.

**Comment by David-Estevez** [comment]
Cosas que he visto (a grandes rasgos):

* El Arduino tiene interrupciones en los pines 2 y 3. Ya que estás usando encoders, te  interesaría tener cada uno de estos pines conectados a un encoder distintos (para poder usar interrupciones con los dos encoders).
* La placa es simple y hay espacio de sobra, así que podrías darle más grosor a las pistas, añadir taladros para fijarla al robot, e incluso añadir algún logo, link a este repo, etc.

**Comment by Ruben-MR** [comment]
Perfecto, le echaré un vistazo a esas dos cosas, gracias.
Dejaré la issue abierta para una vez hechos los cambios, dar el visto bueno final antes de encargarla.

**Comment by David-Estevez** [comment]
Me parece bien. Si tienes alguna duda coméntamela!

**Comment by Ruben-MR** [comment]
Ya está subida la nueva versión de la placa, está en un zip. Lo único que falta por rematar es el tema del logo que me ha resultado tarea imposible. El logo se encuentra también en el zip.

**Comment by David-Estevez** [comment]
No sé si he revisado la última versión, pero tienes una pista sin conectar (VCC).

**Comment by Ruben-MR** [comment]
Los documentos están en un zip llamado PCB sumo v2. Lo de esa conexión VCC es básicamente que no hay forma de unirla, hablamos de si eso hacer un puente con un cable extra.

**Comment by David-Estevez** [comment]
...o usar la otra cara de la PCB? :wink:

**Comment by Ruben-MR** [comment]
Ya está resubido con el problemilla coregido, la cara trasera estaba ocupada en su totalidad por la zona de  relleno de GND, pero ya está hecho un apaño, esperemos que ya esté.

**Comment by David-Estevez** [comment]
Revisión subida: https://github.com/asrob-uc3m/ASROB-sumo/pull/10

**Comment by David-Estevez** [comment]
Todo ok!
