### ISSUE TITLE
Organizar el repo

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/ASROB-sumo#9]
Me está asaltando el TOC al ver todo en la misma carpeta... te importa que lo ordene un poco @Ruben-MR ??

**Comment by Ruben-MR** [comment]
Adelante, yo no lo he hecho porque no tengo muy claro cómo.
Lo agradecería también ahora que lo mencionas...

**Comment by David-Estevez** [comment]
Lo he hecho en la rama `limpieza`. Échale un ojo a ver si te parece todo ok y si te mola lo mergeamos a master.

**Comment by Ruben-MR** [comment]
Está perfectamente, podemos proceder a combinar. Gracias.

**Comment by David-Estevez** [comment]
Hecho en 1cc65b2  A partir de ahora, trabajemos sobre esos ficheros!
